# Generated by Django 5.2.12 on 2026-05-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):
    """Add notes support to episode watches and their history."""

    dependencies = [
        ("app", "0060_fix_reopened_completed_tv_seasons"),
    ]

    operations = [
        migrations.AddField(
            model_name="episode",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="historicalepisode",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
    ]
