# Generated by Django 5.2.16 on 2026-08-15 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_add_episode_notes'),
        ('app', '0064_restore_tz_shifted_media_dates'),
    ]

    operations = [
    ]
